/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MikButton {
    'buttonClick': (e: MouseEvent) => void;
    'mikButtonColor': string;
    'mikButtonDisabled': boolean;
    'mikButtonIcon': string;
    'mikButtonLoading': false;
    'mikButtonRadius': boolean;
    'mikButtonSize': string;
    'mikButtonTextAlign': string;
  }
  interface MikCard {
    'mikCardAuthor': string;
    'mikCardContentMessage': string;
    'mikCardId': string;
    'mikCardImage'?: string;
    'mikCardTitle': string;
  }
  interface MyComponent {}
}

declare global {


  interface HTMLMikButtonElement extends Components.MikButton, HTMLStencilElement {}
  var HTMLMikButtonElement: {
    prototype: HTMLMikButtonElement;
    new (): HTMLMikButtonElement;
  };

  interface HTMLMikCardElement extends Components.MikCard, HTMLStencilElement {}
  var HTMLMikCardElement: {
    prototype: HTMLMikCardElement;
    new (): HTMLMikCardElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'mik-button': HTMLMikButtonElement;
    'mik-card': HTMLMikCardElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface MikButton extends JSXBase.HTMLAttributes<HTMLMikButtonElement> {
    'buttonClick'?: (e: MouseEvent) => void;
    'mikButtonColor'?: string;
    'mikButtonDisabled'?: boolean;
    'mikButtonIcon'?: string;
    'mikButtonLoading'?: false;
    'mikButtonRadius'?: boolean;
    'mikButtonSize'?: string;
    'mikButtonTextAlign'?: string;
    'onMikButtonClick'?: (event: CustomEvent<any>) => void;
  }
  interface MikCard extends JSXBase.HTMLAttributes<HTMLMikCardElement> {
    'mikCardAuthor'?: string;
    'mikCardContentMessage'?: string;
    'mikCardId'?: string;
    'mikCardImage'?: string;
    'mikCardTitle'?: string;
  }
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {}

  interface IntrinsicElements {
    'mik-button': MikButton;
    'mik-card': MikCard;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


